// Generated by CoffeeScript 1.3.3
(function() {
  var should;

  should = chai.should();

  describe('tree', function() {
    var elm, scope;
    elm = null;
    scope = null;
    beforeEach(module('$angularTree'));
    beforeEach(inject(function($rootScope, $compile) {
      elm = angular.element('<div angular-tree data-options="treeOptions"></div>');
      scope = $rootScope;
      scope.treeOptions = {
        expandedIconClass: 'icon-chevron-down',
        collapsedIconClass: 'icon-chevron-right',
        getChildren: function(node, cb) {
          return cb([
            {
              label: 'hello'
            }, {
              label: 'hi'
            }
          ]);
        }
      };
      $compile(elm)(scope);
      return scope.$digest();
    }));
    return it('should get 2 root notes at the beginning', function() {
      var nodes;
      nodes = elm.find('div.angular-tree-node');
      nodes.length.should.equal(2);
      $(nodes[0]).find('.angular-tree-node-expander').hasClass('icon-chevron-right').should.equal(true);
      return $(nodes[1]).find('.angular-tree-node-expander').hasClass('icon-chevron-right').should.equal(true);
    });
  });

}).call(this);
